-- Enable UUID extension if needed (optional)
-- create extension if not exists "uuid-ossp";

-- 1. Measurements Table
create table if not exists measurements (
  id bigint generated by default as identity primary key,
  time timestamptz not null,
  fog float,
  temperature float,
  humidity float
);

-- 2. FSO Companies
create table if not exists companies_fso (
  id bigint generated by default as identity primary key,
  name text not null
);

-- 3. FSO Systems
create table if not exists systems_fso (
  id bigint generated by default as identity primary key,
  name text not null,
  tx_power float,
  tx_power_unit text, -- 'mW' or 'dBm'
  rx_sensitivity float,
  rx_lens_diameter float,
  directivity float,
  wavelength float,
  company_id bigint references companies_fso(id)
);

-- 4. RF Companies
create table if not exists companies_rf (
  id bigint generated by default as identity primary key,
  name text not null
);

-- 5. RF Systems
create table if not exists systems_rf (
  id bigint generated by default as identity primary key,
  name text not null,
  tx_power float,
  tx_power_unit text,
  rx_sensitivity float,
  frequency float,
  gain float,
  company_id bigint references companies_rf(id)
);

-- Sample Data (Optional - Uncomment to insert)
/*
insert into companies_fso (name) values ('Canon'), ('Des');
insert into systems_fso (name, tx_power, tx_power_unit, rx_sensitivity, rx_lens_diameter, directivity, wavelength, company_id) 
values 
('Canobeam DT-110', 30, 'mW', -34, 20, 4, 785, 1),
('Canobeam DT-120', 30, 'mW', -34, 20, 4, 785, 1);
*/
