
-- 1. Measurements Table
create table if not exists measurements (
  id bigint generated by default as identity primary key,
  time timestamptz not null,
  fog float,
  temperature float,
  humidity float
);

-- 2. FSO Companies
create table if not exists companies_fso (
  id bigint generated by default as identity primary key,
  name text not null
);

-- 3. FSO Systems
create table if not exists systems_fso (
  id bigint generated by default as identity primary key,
  name text not null,
  tx_power float,
  tx_power_unit text, -- 'mW' or 'dBm'
  rx_sensitivity float,
  rx_lens_diameter float,
  directivity float,
  wavelength float,
  company_id bigint references companies_fso(id)
);

-- 4. RF Companies
create table if not exists companies_rf (
  id bigint generated by default as identity primary key,
  name text not null
);

-- 5. RF Systems
create table if not exists systems_rf (
  id bigint generated by default as identity primary key,
  name text not null,
  tx_power float,
  tx_power_unit text,
  rx_sensitivity float,
  frequency float,
  gain float,
  company_id bigint references companies_rf(id)
);

