-- Migration: create iot schema and tables used by seed.ts
-- This file is intended to be executed in a Postgres-compatible database (Supabase).

-- Dimension tables
CREATE TABLE IF NOT EXISTS iot.dim_node (
  node_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS iot.dim_sensor (
  sensor_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS iot.dim_key_value (
  key_value_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_name text NOT NULL,
  unit text,
  value_num numeric,
  value_text text
);

-- Fact table with foreign keys
CREATE TABLE IF NOT EXISTS iot.fact_meteo (
  fact_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  node_id integer REFERENCES iot.dim_node(node_id),
  sensor_id integer REFERENCES iot.dim_sensor(sensor_id),
  key_value_id bigint REFERENCES iot.dim_key_value(key_value_id)
);

-- Raw measurement table (used by the seed script)
CREATE TABLE IF NOT EXISTS iot.raw_meteo (
  ts timestamptz NOT NULL,
  node text NOT NULL,
  sensor text NOT NULL,
  key text NOT NULL,
  value double precision NOT NULL,
  unit text,
  value_text text,
  CONSTRAINT raw_meteo_pkey PRIMARY KEY (ts, node, sensor, key)
);
